package db.migration;

import org.flywaydb.core.api.MigrationVersion;
import org.flywaydb.core.api.migration.MigrationInfoProvider;
import org.flywaydb.core.api.migration.spring.SpringJdbcMigration;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
public class V1__Database_scheme_initialization implements SpringJdbcMigration, MigrationInfoProvider {

  @Override
  public void migrate(JdbcTemplate jdbcTemplate) throws Exception {

    jdbcTemplate.execute("create table user_account (id bigint generated by default as identity (start with 1), login varchar(255), name varchar(255), password varchar(255), role_id bigint, primary key (id))");
    jdbcTemplate.execute("create table attendance (id bigint generated by default as identity (start with 1), class_instance_id bigint, primary key (id))");
    jdbcTemplate.execute("create table attendance_class_seat (attendance_id bigint not null, class_seat_id bigint not null)");
    jdbcTemplate.execute("create table attendant (id bigint generated by default as identity (start with 1), pupil boolean not null, personal_data_id bigint, user_account_id bigint, primary key (id))");
    jdbcTemplate.execute("create table class (id bigint generated by default as identity (start with 1), active boolean not null, conducting_teacher_id bigint, event_id bigint, room_id bigint, schedule_id bigint, primary key (id))");
    jdbcTemplate.execute("create table class_category (id bigint generated by default as identity (start with 1), access_restriction boolean not null, attendance_required boolean not null, color varchar(255), description varchar(255), name varchar(255) not null, primary key (id))");
    jdbcTemplate.execute("create table class_instance (id bigint generated by default as identity (start with 1), description varchar(255), name varchar(255), status varchar(255), true_time timestamp, class_id bigint, true_attending_teacher_id bigint, primary key (id))");
    jdbcTemplate.execute("create table class_seat (id bigint generated by default as identity (start with 1), attendance_staus boolean not null, is_teacher boolean not null, fixed_id bigint, temporary_id bigint, primary key (id))");
    jdbcTemplate.execute("create table class_seat_slot (id bigint generated by default as identity (start with 1), status varchar(255), attendant_id bigint, primary key (id))");
    jdbcTemplate.execute("create table class_template (id bigint generated by default as identity (start with 1), capacity integer not null, description varchar(255), duration integer, name varchar(255) not null, required_level_id bigint, type_id bigint, primary key (id))");
    jdbcTemplate.execute("create table class_visit (id bigint generated by default as identity (start with 1), number integer not null, program_template_id bigint not null, primary key (id))");
    jdbcTemplate.execute("create table level (id bigint generated by default as identity (start with 1), description varchar(255), name varchar(255), primary key (id))");
    jdbcTemplate.execute("create table notification (id bigint generated by default as identity (start with 1), occurence varbinary(255), type integer, primary key (id))");
    jdbcTemplate.execute("create table notification_settings (id bigint generated by default as identity (start with 1), type integer, primary key (id))");
    jdbcTemplate.execute("create table personal_data (id bigint generated by default as identity (start with 1), active boolean not null, additional_data varchar(255), name varchar(255), primary key (id))");
    jdbcTemplate.execute("create table program (id bigint generated by default as identity (start with 1), active boolean not null, date_of_issue timestamp, discount double, program_template_id bigint, schedule_id bigint, primary key (id))");
    jdbcTemplate.execute("create table program_instance (id bigint generated by default as identity (start with 1), notes varchar(255), status varchar(255), true_time timestamp, program_id bigint, true_attending_teacher_id bigint, primary key (id))");
    jdbcTemplate.execute("create table program_instance_attendent (program_instance_id bigint not null, attendent_id bigint not null)");
    jdbcTemplate.execute("create table program_template (id bigint generated by default as identity (start with 1), active boolean not null, date_of_issue timestamp, description varchar(255), name varchar(255) not null, tarif_id bigint, primary key (id))");
    jdbcTemplate.execute("create table reminder (id bigint generated by default as identity (start with 1), details varchar(255), name varchar(255), primary key (id))");
    jdbcTemplate.execute("create table role (id bigint generated by default as identity (start with 1), description varchar(255), name varchar(255) not null, primary key (id))");
    jdbcTemplate.execute("create table room (id bigint generated by default as identity (start with 1), description varchar(255), name varchar(255) not null, primary key (id))");
    jdbcTemplate.execute("create table schedule (id bigint generated by default as identity (start with 1), end_date timestamp, reccurence_type varchar(255), scheduled_day integer, scheduled_day_of_month integer not null, scheduled_month integer, scheduled_time varbinary(255), start_date timestamp, notification_settings_id bigint, primary key (id))");
    jdbcTemplate.execute("create table skill (id bigint generated by default as identity (start with 1), attendant_id bigint not null, category_id bigint, level_id bigint, primary key (id))");
    jdbcTemplate.execute("create table tarif (id bigint generated by default as identity (start with 1), date_of_issue timestamp, description varchar(255), name varchar(255) not null, value double, primary key (id))");
    jdbcTemplate.execute("create table user_account_notification (user_account_id bigint not null, notification_id bigint not null, primary key (user_account_id, notification_id))");
    jdbcTemplate.execute("alter table user_account add constraint FK_qleu8ddawkdltal07p8e6hgva foreign key (role_id) references role");
    jdbcTemplate.execute("alter table attendance add constraint FK_2xwsf9b3a8wojgx4ge9co2a67 foreign key (class_instance_id) references class_instance");
    jdbcTemplate.execute("alter table attendance_class_seat add constraint FK_c6fkl7aye5g5qbcep8aiwuwug foreign key (class_seat_id) references class_seat");
    jdbcTemplate.execute("alter table attendance_class_seat add constraint FK_2o5m8d77hxf9duj10xqdg4vu6 foreign key (attendance_id) references attendance");
    jdbcTemplate.execute("alter table attendant add constraint FK_fwjnvxqhl6mav3uoe2poabatd foreign key (personal_data_id) references personal_data");
    jdbcTemplate.execute("alter table attendant add constraint FK_lbv6rkm880to3jnsvi0epd2hb foreign key (user_account_id) references user_account");
    jdbcTemplate.execute("alter table class add constraint FK_f83bx6968f8ia9wjpju56bs38 foreign key (conducting_teacher_id) references attendant");
    jdbcTemplate.execute("alter table class add constraint FK_68b7sclcrqmgwf3u9ujoujao9 foreign key (event_id) references class_template");
    jdbcTemplate.execute("alter table class add constraint FK_90x3cfjcncab71at5esuw5htj foreign key (room_id) references room");
    jdbcTemplate.execute("alter table class add constraint FK_ns0jgnrnkrrlgu8gdliikdapa foreign key (schedule_id) references schedule");
    jdbcTemplate.execute("alter table class_instance add constraint FK_if5d7bps937dknfulxu5ofwns foreign key (class_id) references class");
    jdbcTemplate.execute("alter table class_instance add constraint FK_e7ef70kfk53f2kav85cn9jalm foreign key (true_attending_teacher_id) references attendant");
    jdbcTemplate.execute("alter table class_seat add constraint FK_799lrgofa18ulua2lrgbpq9rp foreign key (fixed_id) references class_seat_slot");
    jdbcTemplate.execute("alter table class_seat add constraint FK_m36h5c3nnps4spybj1mfxaicx foreign key (temporary_id) references class_seat_slot");
    jdbcTemplate.execute("alter table class_seat_slot add constraint FK_sayuoefjv2ir80ud8wgge8vgw foreign key (attendant_id) references attendant");
    jdbcTemplate.execute("alter table class_template add constraint FK_p3uxv34kgh5fwf1k793o2h3c6 foreign key (required_level_id) references level");
    jdbcTemplate.execute("alter table class_template add constraint FK_gcgwr5lurdnx2xgcarr6oopi8 foreign key (type_id) references class_category");
    jdbcTemplate.execute("alter table class_visit add constraint FK_cja0mjai3bytgyiwktuc3sfjh foreign key (program_template_id) references program_template");
    jdbcTemplate.execute("alter table program add constraint FK_q61skn48g9v99725aibwb6euk foreign key (program_template_id) references program_template");
    jdbcTemplate.execute("alter table program add constraint FK_bufw5sr7903twp1bfyn2nwddv foreign key (schedule_id) references schedule");
    jdbcTemplate.execute("alter table program_instance add constraint FK_r7qw6218festrutteo3dwjuu4 foreign key (program_id) references program");
    jdbcTemplate.execute("alter table program_instance add constraint FK_iv8lls0gqxkt159sff04c5wva foreign key (true_attending_teacher_id) references attendant");
    jdbcTemplate.execute("alter table program_instance_attendent add constraint FK_1a8o9cfxk2wu0cgyy3gpu0rhp foreign key (attendent_id) references attendant");
    jdbcTemplate.execute("alter table program_instance_attendent add constraint FK_ibaubva2hvn9gs54r9iud4tdh foreign key (program_instance_id) references program_instance");
    jdbcTemplate.execute("alter table program_template add constraint FK_l29dc5c3t2s3wif7kpbxsqosp foreign key (tarif_id) references tarif");
    jdbcTemplate.execute("alter table schedule add constraint FK_sl1nqd1dc9lh68n2hpwgy3j4p foreign key (notification_settings_id) references notification_settings");
    jdbcTemplate.execute("alter table skill add constraint FK_sea3r0f460ipgmraivigstkp0 foreign key (attendant_id) references attendant");
    jdbcTemplate.execute("alter table skill add constraint FK_a9o0v9wgd0r69og794wg19eks foreign key (category_id) references class_category");
    jdbcTemplate.execute("alter table skill add constraint FK_q2jq9pqtq7ris6lta8dk65i4h foreign key (level_id) references level");
    jdbcTemplate.execute("alter table user_account_notification add constraint FK_57br8073hgsj70sww9gwv88to foreign key (notification_id) references notification");
    jdbcTemplate.execute("alter table user_account_notification add constraint FK_hrv2lmyjlt3ken6hk2f4sg1e foreign key (user_account_id) references user_account");

  }

  @Override
  public MigrationVersion getVersion() {
    return MigrationVersion.fromVersion("1");

  }

  @Override
  public String getDescription() {
    return "Default database scheme initialization";
  }

}